# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from datasets import load_dataset

dataset = load_dataset("go_emotions")

print(dataset)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def simplify_labels(example):
    example["label"] = example["labels"][0] if len(example["labels"]) > 0 else 0
    return example

dataset = dataset.map(simplify_labels)

def tokenize_function(example):
    result = tokenizer(example["text"], padding="max_length", truncation=True)
    result["labels"] = example["label"]
    return result

tokenized_datasets = dataset.map(tokenize_function, batched=True)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=28
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,  # faster
    per_device_eval_batch_size=16,
    num_train_epochs=3,  # only 1 epoch for now
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
)

dataset = dataset.remove_columns(["labels"])

small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(5000))
small_eval_dataset = tokenized_datasets["validation"].shuffle(seed=42).select(range(1000))

import torch
print(torch.cuda.is_available())

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
)

trainer.train()

trainer.save_model("emotion_model")

from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="emotion_model",
    tokenizer="distilbert-base-uncased",
    return_all_scores=True
)

text = "I feel very sad and tired"
result = classifier(text)

print(result)

def get_emotion(text):
    result = classifier(text)[0]
    label = result["label"]

    # extract number from label
    label_index = int(label.split("_")[1])

    return label_index

print(get_emotion("I feel very sad"))

emotion_map = {
    0: "admiration",
    1: "amusement",
    2: "anger",
    3: "annoyance",
    4: "approval",
    5: "caring",
    6: "confusion",
    7: "curiosity",
    8: "desire",
    9: "disappointment",
    10: "disapproval",
    11: "disgust",
    12: "embarrassment",
    13: "excitement",
    14: "fear",
    15: "gratitude",
    16: "grief",
    17: "joy",
    18: "love",
    19: "nervousness",
    20: "optimism",
    21: "pride",
    22: "realization",
    23: "relief",
    24: "remorse",
    25: "sadness",
    26: "surprise",
    27: "neutral"
}

def predict_emotion(text):
    index = get_emotion(text)
    return emotion_map[index]

print(predict_emotion("I feel very sad"))