# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from datasets import load_dataset

dataset = load_dataset("go_emotions")

print(dataset)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def simplify_labels(example):
    example["label"] = example["labels"][0] if len(example["labels"]) > 0 else 0
    return example

dataset = dataset.map(simplify_labels)

def tokenize_function(example):
    result = tokenizer(example["text"], padding="max_length", truncation=True)
    result["labels"] = example["label"]
    return result

tokenized_datasets = dataset.map(tokenize_function, batched=True)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=28
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,  # faster
    per_device_eval_batch_size=16,
    num_train_epochs=1,  # only 1 epoch for now
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
)

dataset = dataset.remove_columns(["labels"])

small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(2000))
small_eval_dataset = tokenized_datasets["validation"].shuffle(seed=42).select(range(500))

import torch
print(torch.cuda.is_available())

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
)

trainer.train()

trainer.save_model("emotion_model")